show X status properly if Fuzzer fails

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -79,7 +79,9 @@ jobs:
     #   # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
     #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
     #   run: ctest --build-config ${{ matrix.build_type }}
-    - name: run tests
+    - name: Run fuzzer
+      id: fuzzer
+      continue-on-error: true  # Allows next steps to run even if this fails
       run: |
         xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/BoxTests 2>&1 | tee fuzzer_log.txt
 
@@ -89,3 +91,11 @@ jobs:
       with:
         name: fuzzer-logs
         path: fuzzer_log.txt
+
+    - name: Check test result
+      if: always()
+      run: |
+        if [ "${{ steps.fuzzer.outcome }}" != "success" ]; then
+          echo "Fuzzer test failed"
+          exit 1
+        fi
