report correct test result in ci (#157)
* check test result

* rename "fuzzer" to "test"

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -73,21 +73,23 @@ jobs:
       run: |
         ccache -s
         ccache -p
-
-    # - name: Test
-    #   working-directory: ${{ steps.strings.outputs.build-output-dir }}
-    #   # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-    #   run: ctest --build-config ${{ matrix.build_type }}
-    - name: Run fuzzer
+    - name: Run tests
+      id: test
       continue-on-error: true  # Allows next steps to run even if this fails
       run: |
         set -o pipefail
-        xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/BoxTests 2>&1 | tee fuzzer_log.txt
+        xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/BoxTests 2>&1 | tee test_log.txt
 
-    - name: Upload fuzzer log
+    - name: Upload test log
       if: always()  # This ensures it uploads even if the test fails
       uses: actions/upload-artifact@v4
       with:
-        name: fuzzer-logs
-        path: fuzzer_log.txt
+        name: test-logs
+        path: test_log.txt
+    - name: Check test result
+      if: always()
+      run: |
+        if [ "${{ steps.test.outcome }}" != "success" ]; then
+          echo "Tests failed"
+          exit 1
+        fi
