run fakemain in ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -78,14 +78,20 @@ jobs:
       continue-on-error: true  # Allows next steps to run even if this fails
       run: |
         set -o pipefail
-        xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/BoxTests 2>&1 | tee test_log.txt
+        xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/BoxTests_artefacts/Debug/BoxTests 2>&1 | tee test_log.txt
+    - name: Run "Fake Main" test
+      id: fake_main_test
+      continue-on-error: true  # Allows next steps to run even if this fails
+      run: |
+        set -o pipefail
+        xvfb-run -a --server-args="-screen 0 1280x1024x24" ./build/FakeMain_artefacts/Debug/FakeMain 2>&1 | tee fake_main_test_log.txt
 
     - name: Upload test log
       if: always()  # This ensures it uploads even if the test fails
       uses: actions/upload-artifact@v4
       with:
         name: test-logs
-        path: test_log.txt
+        path: *test_log.txt
     - name: Check test result
       if: always()
       run: |
